# Generated by Django 5.0.7 on 2024-08-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_kshitij'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='kshitij',
        ),
    ]
