# Generated by Django 5.0.7 on 2024-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_remove_tweet_kshitij'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='kshitij',
            field=models.TextField(default='  '),
            preserve_default=False,
        ),
    ]
